// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxysql/proxysql.proto

package proxysql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryDigest struct {
	HostGroup            int64    `protobuf:"varint,1,opt,name=HostGroup,proto3" json:"HostGroup,omitempty"`
	Digest               string   `protobuf:"bytes,4,opt,name=Digest,proto3" json:"Digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDigest) Reset()         { *m = QueryDigest{} }
func (m *QueryDigest) String() string { return proto.CompactTextString(m) }
func (*QueryDigest) ProtoMessage()    {}
func (*QueryDigest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxysql_dd3e6a5e3d491c46, []int{0}
}
func (m *QueryDigest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDigest.Unmarshal(m, b)
}
func (m *QueryDigest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDigest.Marshal(b, m, deterministic)
}
func (dst *QueryDigest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDigest.Merge(dst, src)
}
func (m *QueryDigest) XXX_Size() int {
	return xxx_messageInfo_QueryDigest.Size(m)
}
func (m *QueryDigest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDigest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDigest proto.InternalMessageInfo

func (m *QueryDigest) GetHostGroup() int64 {
	if m != nil {
		return m.HostGroup
	}
	return 0
}

func (m *QueryDigest) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryDigest)(nil), "QueryDigest")
}

func init() { proto.RegisterFile("proxysql/proxysql.proto", fileDescriptor_proxysql_dd3e6a5e3d491c46) }

var fileDescriptor_proxysql_dd3e6a5e3d491c46 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0xaf,
	0xa8, 0x2c, 0x2e, 0xcc, 0xd1, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x95, 0x9c, 0xb9,
	0xb8, 0x03, 0x4b, 0x53, 0x8b, 0x2a, 0x5d, 0x32, 0xd3, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38,
	0x3d, 0xf2, 0x8b, 0x4b, 0xdc, 0x8b, 0xf2, 0x4b, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x10, 0x75, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50,
	0x5e, 0x12, 0x1b, 0xd8, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x57, 0x54, 0xe4,
	0x66, 0x00, 0x00, 0x00,
}
